# Site settings
title: "Foo Bar"
description: "A repository of my thoughts about random stuff, sometimes video games."
baseurl: "" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: ""
author: "Shivanju"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics: UA-126563695-1
disqus_shortname: shivanju.disqus.com

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
